#!/bin/bash

# Nagios plugin to check for usage on all block devices.
#
# You should place the warning and critical thresholds below.

warning=80
critical=90

warning_disks=""
critical_disks=""

for disk in $(df -h | grep ^/dev | awk '{print $1}' | awk -F"/" '{print $NF}') ; do
    usage="$(df -h | grep "$disk" | sed "s/%//" | awk '{print $5}')"
    if [ "$usage" -ge $critical ]; then
      critical_disks+="$disk($usage%) "
    fi

    if [ "$usage" -ge $warning ] && [ "$usage" -lt $critical ]; then
      warning_disks+="$disk($usage%) "
    fi
done

if [ "$critical_disks" ]; then
  echo "Critical - Usage over $critical% for $critical_disks"
  exit 2
fi

if [ "$warning_disks" ]; then
  echo "Warning - Usage over $warning% for $warning_disks"
  exit 1
fi

echo "OK"
exit 0
