#!/bin/sh
#
# Munin plugin to monitor Oracle tablespace usage
#
# Author: Konstantinos Tompoulidis (kostikas@gmail.com) on 10th of March 2016
# (Based on the munin plugin by (Joan Carles Soler)
#
# Licenced under GPL v2.
#
# Usage: Provide the parameters listed below
#
# Parameters:
#   autoconf
#    suggest
#     config   (required)
#
# Config variables:
#
#         SID - Database to use. Defaults to "orcl" if "suggest" is not used.
#        USER - user with read permission to the v$session view (MANDATORY)
#      PASSWD - the password of the above user
# ORACLE_HOME - The home directory of the ORACLE database (not the oracle user)
#
# Magic markers
#%# family=auto
#%# capabilities=autoconf suggest

SID=${0#*_*_*_}   # Get the SID from the filename (wildcard plugin)
USER=           # Mandatory - Ideal: a user with only the required privileges
PASSWD=         # Mandatory
ORACLE_HOME=    # Mandatory

lsnrctl="$ORACLE_HOME/bin/lsnrctl"
sqlplus="$ORACLE_HOME/bin/sqlplus"

if [ -z "$SID" ]
then
    SID="orcl"
fi

# Autoconf is available
if [ "$1" = "autoconf" ] ; then echo yes ; exit 0 ; fi

if [ -z "$ORACLE_HOME" ]; then
    echo "ORACLE_HOME must be set."
    exit 1
fi

export ORACLE_HOME

# Get available SIDs for suggest to work
if [ "$1" = "suggest" ] ; then
    if [ "$(pgrep pmon)" ]; then
#        su oracle -c "$lsnrctl status"|grep "  Instance "|cut -d\" -f2|sort|uniq
        su oracle -c "$lsnrctl status"| grep "^Service " | cut -d\" -f2 | egrep -v "^cdb$|^cdbXDB$"
    fi
    exit 0
fi

# Provide munin configuration
if [ "$1" = "config" ] ; then
    if [ -z "$USER" ] || [ -z "$PASSWD" ]; then
        echo "USER and PASSWD variables must be set."
        exit 1
    fi
    echo "graph_title Oracle tablespace usage from $SID"
    echo "graph_args --base 1000 -l 0 -u 100"
    echo "graph_vlabel tablespace usage"
    echo "graph_category Oracle"
    echo "graph_info This graph shows the tablespace usage (in %)"
    echo "graph_scale no"
    for i in $(echo "`$sqlplus -s ${USER}/${PASSWD}@$SID << EOF | grep -v '^$' | grep -v "rows selected"
set pagesize 0
SELECT unique tablespace_name from dba_data_files;
EOF`") ; do
        echo "$i.label $i"
        echo "$i.info $i tablespace"
        echo "$i.type GAUGE"
        echo "$i.draw LINE2"
    done
    exit 0
fi

#get tablespace usage
echo "`$sqlplus -s ${USER}/${PASSWD}@$SID << EOF | grep -v '^$' | awk '{print $1".value "$2/$3*100}' 2>/dev/null | egrep [0-9] | grep -v "rows selected"
set pagesize 0
select a.tablespace_name, b.free,a.total,trunc(b.free/a.total * 1000) / 10 prc from ( select tablespace_name,sum(bytes) total from dba_data_files group by tablespace_name) A, ( select tablespace_name,sum(bytes) free from dba_free_space group by tablespace_name) B where a.tablespace_name=b.tablespace_name;
EOF`"

